#! /bin/bash
nocolor="\033[0m"
red="\033[0;31m"
green="\033[0;32m"
yellow="\033[0;33m"
option=$1
directory=$2
main=/tmp

cat << "help"
        __  ___                                  ____  _     
       /  |/  ____ _____  ____ _____ ____       / __ \(______
      / /|_/ / __ `/ __ \/ __ `/ __ `/ _ \     / / / / / ___/
     / /  / / /_/ / / / / /_/ / /_/ /  __/    / /_/ / / /    
    /_/  /_/\__,_/_/ /_/\__,_/\__, /\________/_____/_/_/     
                             /____/    /_____/  
			
            coded-by: bakri | twitter: @b7kri_17
help
printf "\n${green}--------------------------------------------------------------------------${nocolor}\n"
printf "${green}using : sudo  $0 -option <dir name or full path>${nocolor}\n"
printf "${green}Eg : sudo $0 -sort /home/bakri/Downloads${nocolor}\n"
printf "${green}             -option { --help --sort ${red}--delete ${nocolor}${green}}${nocolor}\n"
printf "${green}--------------------------------------------------------------------------${nocolor}\n"
case $option in 
    "-s" | "--sort")
	if [ ! $(whoami) == 'root' ]; then
		printf "${red} useing sudo before script name ${nocolor}\n"
		printf "${green} Eg : sudo $0 -sort /home/bakri/Downloads${nocolor}\n"
		exit
	fi
	if [ ! -d $directory ]; then
		printf "$directory not found \n"	
		exit
	fi
        chmod -R 777 $directory
        find $directory -name "*" | grep -Eo "(\.\b[a-zA-Z0-9]+)" | sed -E 's:\.::g' | sort | uniq | grep -v -E '^[0-9]+$' > $main/extension_m.txt
        for i in $(cat $main/extension_m.txt);do
            if [ ! -e $directory/$i ]; then
                mkdir $directory/$i
            fi
            find $directory -name "*.$i" > $main/trans.txt
            IFS=''
            while read orign ;do
            filename=$(find "$orign" -name "*.$i" -exec basename {} \;)
            if [ $orign != $directory/$i/$filename ]; then
                  mv $orign $directory/$i/ 2> /dev/null
            fi
        done < $main/trans.txt
           
       done
       find $directory -empty -type d > $main/l.txt
       IFS=''
       while read l; do
             rmdir $l     
       done < $main/l.txt
       find $directory -size 0 > $main/tt.txt
       IFS=''
       while read l; do
           rm -r $l   
       done < $main/tt.txt
       echo -ne "Sorting Process : ${red}######                                             (10%)${nocolor}\r"
       sleep 1
       echo -ne "Sorting Process : ${red}##########                                         (20%)${nocolor}\r"
       sleep 1
       echo -ne "Sorting Process : ${red}###############                                    (30%)${nocolor}\r"
       sleep 1
       echo -ne "Sorting Process : ${yellow}####################                               (40%)${nocolor}\r"
       sleep 1
       echo -ne "Sorting Process : ${yellow}#########################                         (50%)${nocolor}\r"
       sleep 1
       echo -ne "Sorting Process : ${yellow}##############################                     (60%)${nocolor}\r"
       sleep 1
       echo -ne "Sorting Process : ${green}###################################                (70%)${nocolor}\r"
       sleep 1
       echo -ne "Sorting Process : ${green}########################################           (80%)${nocolor}\r"
       sleep 1
       echo -ne "Sorting Process : ${green}#############################################      (90%)${nocolor}\r"
       sleep 1
       echo -ne "Sorting Process : ${green}##################  Complate  #################### (100%)${nocolor}\r"
       sleep 1
       echo -ne '\n'
       chmod -R 777 $directory

    ;;
    "-d" | "--delete")
    if [ -e $directory ]; then
        rm -r $directory
        if [ $? -eq 0 ]; then
               #printf "$directory ${red}Deleted${nocolor} \n"
               echo -ne "Deleteing Process : ${green}##############                                    (80%)${nocolor}\r"
               sleep 1
               echo -ne "Deleteing Process : ${yellow}############################                       (90%)${nocolor}\r"
               sleep 1
               echo -ne "Deleteing Process : ${red}##################  Complate  #################### (100%)${nocolor}\r"
               sleep 1
               echo -ne '\n'
        fi
       
    else
        printf "Directory $directory Not Found \n"
    fi
    ;;
    "-h" | "--help")
cat << "n"
      Script For Directory sorting or deleteing
      option:
      --sort   | -s       :sort file in directory
      --delete | -d       :delete directory
      --help   | -h       :how this menu
n
    ;;
    *)
    printf "Select Option -sort or delete only\n"
    ;;
    esac
